from typing import Any
from typing import Optional


class Item:
    """Item class. Generated by the environment.
    
    See also:
        econsimulacra.envs.base.Environment._generate_items
    """

    def __init__(
        self,
        item_id: int,
        item_name: str,
        config: Optional[dict[str, Any]] = None,
    ) -> None:
        """Initialization.

        Args:
            item_id (int): The unique id for the item.
            item_name (str): The name of the item.
            config (dict[str, Any], Optional): Optional config. If it contains "initialPrice", it is used as the initial price. Defaults to None.
        """
        self.item_id: int = item_id
        self.item_name: str = item_name
        self.price: float
        self.config: dict[str, Any] = config if config is not None else {}
        if "initialPrice" in self.config:
            self.price = self.config["initialPrice"]
        else:
            self.price = 0.0
        self.price_set_by: Optional[int] = None

    def get_price(self) -> float:
        """Get the price of the item.

        Returns:
            float: The price of the item.
        """
        return self.price

    def set_price(self, price: float, set_by: Optional[int] = None) -> None:
        """Set the price of the item.

        Args:
            price (float): The new price of the item.
            set_by (int, Optional): The id of the agent who set the price. Defaults to None.
        """
        self.price = price
        self.price_set_by = set_by

    def __repr__(self):
        return f"Item(id={self.item_id}, name={self.item_name}, price={self.price}, price_set_by={self.price_set_by})"
