from typing import Any, Optional


class Item:
    """Item class. Generated by the environment.

    See also:
        econsimulacra.envs.base.Environment._generate_items
    """

    def __init__(
        self,
        item_id: int,
        item_name: str,
        config: Optional[dict[str, Any]] = None,
    ) -> None:
        """Initialization.

        Args:
            item_id (int): The unique id for the item.
            item_name (str): The name of the item.
            config (dict[str, Any], optional): Optional config. If it contains "initialPrice", it is
                used as the initial price. If it contains "stressEffects", it is used as the stress
                reduction effects when the item is consumed. Defaults to None.

        Note:
            The "stressEffects" config key maps stress component names to the amount of stress they
            reduce upon consumption. Supported keys:
                - "hunger": reduces physical hunger stress.
                - "fatigue": reduces physical fatigue stress.
                - "life": reduces life (dietary) stress.
                - "financial_affordance": reduces financial affordance stress.
                - "social_satisfaction": reduces social satisfaction stress.
            Example config:
                {
                    "initialPrice": 500.0,
                    "stressEffects": {
                        "hunger": 20.0,
                        "life": 5.0
                    }
                }
        """
        self.item_id: int = item_id
        self.item_name: str = item_name
        self.price: float
        self.config: dict[str, Any] = config if config is not None else {}
        if "initialPrice" in self.config:
            self.price = self.config["initialPrice"]
        else:
            self.price = 0.0
        self.price_set_by: Optional[int] = None
        self.stress_effects: dict[str, float] = self.config.get("stressEffects", {})

    def get_price(self) -> float:
        """Get the price of the item.

        Returns:
            float: The price of the item.
        """
        return self.price

    def set_price(self, price: float, set_by: Optional[int] = None) -> None:
        """Set the price of the item.

        Args:
            price (float): The new price of the item.
            set_by (int, optional): The agent id who set the price. Defaults to None.
        """
        self.price = price
        self.price_set_by = set_by

    def __repr__(self):
        return f"Item(id={self.item_id}, name={self.item_name}, price={self.price}, price_set_by={self.price_set_by})"
