from typing import Any, Optional


class Item:
    """Item class. Generated by the environment.

    See also:
        econsimulacra.envs.base.Environment._generate_items
    """

    def __init__(
        self,
        item_id: int,
        item_name: str,
        config: Optional[dict[str, Any]] = None,
    ) -> None:
        """Initialization.

        Args:
            item_id (int): The unique id for the item.
            item_name (str): The name of the item.
            config (dict[str, Any], optional): Optional config. It may contain
                "initialPrice": The initial price of the item. Defaults to 0.
                "weightInBascket": The weight of the item in the consumer price index (CPI) calculation. Defaults to 1.
                    See also: econsimulacra.memory.stress_utils.calc_stress_from_state_evaluation_history
        """
        self.item_id: int = item_id
        self.item_name: str = item_name
        self.price: float
        self.config: dict[str, Any] = config if config is not None else {}
        if "initialPrice" in self.config:
            self.price = self.config["initialPrice"]
        else:
            self.price = 0.0
        if "weightInBasket" in self.config:
            self.weight_in_basket = self.config["weightInBasket"]
        else:
            self.weight_in_basket = 1.0
        self.price_set_by: Optional[int] = None

    def get_price(self) -> float:
        """Get the price of the item.

        Returns:
            float: The price of the item.
        """
        return self.price

    def set_price(self, price: float, set_by: Optional[int] = None) -> None:
        """Set the price of the item.

        Args:
            price (float): The new price of the item.
            set_by (int, optional): The agent id who set the price. Defaults to None.
        """
        self.price = price
        self.price_set_by = set_by

    def __repr__(self):
        return f"Item(id={self.item_id}, name={self.item_name}, price={self.price}, price_set_by={self.price_set_by})"
