from typing import Any, Optional

from ..llm_services import LLMClient, PersonaBuilder, PromptBuilder
from .base import Agent


class LLMAgent(Agent[dict[str, Any]]):
    """LLM agent that uses a language model to generate actions based on observations.

    The LLMAgent relies on the environment services to provide an LLM client, a prompt builder, and optionally a persona builder.
    The agent constructs prompts based on the current observation and persona (if applicable),
    sends the prompt to the LLM client, and returns the generated response as its action.
    """

    def _setup_env_services(self, env_service_dic: dict[str, Any]) -> None:
        """Setup environment services for the agent based on self.service_dic.

        Args:
            env_service_dic (dict): A dictionary of environment services. This must include:
                - "llmClient": an instance of LLMClient for generating responses from prompts.
                - "promptBuilder": an instance of PromptBuilder for constructing prompts from observations.
                and may include:
                - "personaBuilder": (optional) an instance of PersonaBuilder for constructing persona prompts.

        See also: econsimulacra.envs.base._generate_service_providers,
        econsimulacra.llm_services.clients, econsimulacra.llm_services.prompts,
        econsimulacra.llm_services.personas
        """
        if "llmClient" not in env_service_dic:
            raise ValueError(
                f"LLMAgent {self.agent_name} requires 'llmClient' in env_service_dic."
            )
        self.llm_client: LLMClient = env_service_dic["llmClient"]
        self.persona_builder: Optional[PersonaBuilder] = None
        if "personaBuilder" in env_service_dic:
            self.persona_builder = env_service_dic["personaBuilder"]
            if self.persona_builder is not None:
                self.persona_builder.build_persona(
                    agent_id=self.agent_id,
                    agent_config=self.config.get("personaConfig", {}),
                )
        if "promptBuilder" not in env_service_dic:
            raise ValueError(
                f"LLMAgent {self.agent_name} requires 'promptBuilder' in env_service_dic."
            )
        self.prompt_builder: PromptBuilder = env_service_dic["promptBuilder"]
        self.last_prompt: str = ""

    def self_assign_name(self, config):
        """Assign name to the agent, potentially using the persona builder if available.

        Args:
            config (dict): Configuration dictionary for the agent.
                This may include a "personaConfig" key with configuration for the persona builder.

        See also:
            econsimulacra.llm_services.personas.base.PersonaBuilder
        """
        super().self_assign_name(config)
        if self.persona_builder is not None:
            self.agent_name = self.persona_builder.assign_name(
                agent_id=self.agent_id,
                default_name=self.agent_name,
                config=config.get("personaConfig", {}),
            )

    async def act(self, obs: dict[str, Any]) -> dict[str, Any]:
        """Generate an action based on the current observation.

        Args:
            obs (dict): The current observation for the agent.
                The structure of this dictionary depends on the environment.

        Returns:
            dict: The action generated by the agent based on the current observation.
                The generated action is applied in the environment.

        Note:
            This method constructs a prompt by combining the persona prompt
            (if a persona builder is available) and the observation prompt
            (constructed by the prompt builder).
            It then sends the prompt to the LLM client to generate a response.
        """
        is_sleeping: bool = obs.get("self_is_sleeping", False)
        if is_sleeping:
            return {}
        persona_prompt: str = ""
        if self.persona_builder is not None:
            persona_prompt = self.persona_builder.build_persona_prompt(
                agent_id=self.agent_id
            )
        obs_prompt: str = self.prompt_builder.build_prompt(obs=obs)
        prompt: str = persona_prompt + obs_prompt
        llm_response: dict[str, Any] = await self.llm_client.generate_response(
            prompt=prompt
        )
        self.last_prompt = prompt
        return llm_response
