from __future__ import annotations

import pathlib
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, Generic, Optional, TypeVar

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from rich.console import Console, RenderableType
from rich.panel import Panel

from .records import AgentGenerationRecord
from .store import RecordStore

T = TypeVar("T")


class AnalyzerBase(ABC, Generic[T]):
    """Base Analyzer class. Subclasses should implement the analyze and draw_figs methods.

    The analyze method processes the RecordStore and returns results in a structured format.
    The draw_figs method takes the analysis results and generates figures for visualization.

    Attributes:
        name (str): A unique name for the analyzer, used for organizing results and figure files.
    """

    name: str

    @abstractmethod
    def analyze(self, store: RecordStore) -> T:
        pass

    @abstractmethod
    def draw_figs(
        self,
        result: T,
    ) -> dict[str, Figure]:
        pass

    def get_agent_id2name(self, store: RecordStore) -> dict[int, str]:
        """Utility method to create a mapping from agent IDs to agent names using AgentGenerationRecord.

        Args:
            store (RecordStore): The record store containing the records to analyze.

        Returns:
            dict[int, str]: A dictionary mapping agent IDs to agent names.
        """
        agent_id2name: dict[int, str] = {}
        for record in store.typed(AgentGenerationRecord):
            agent_id2name[record.agent_id] = record.agent_name
        return agent_id2name

    def build_summary(self, result: T) -> RenderableType:
        """Build a rich-renderable summary of the analysis result.

        Subclasses can override this method.
        """
        return Panel.fit(
            f"No summary is implemented for [bold]{self.name}[/bold].",
            title="Analysis Summary",
            border_style="yellow",
        )

    def summarize_results(
        self,
        result: T,
        console: Optional[Console] = None,
    ) -> None:
        """Print the analysis summary using rich."""
        console = console or Console()
        console.print(self.build_summary(result))


class FigureSaver:
    """Utility class for saving figures generated by analyzers."""

    def __init__(
        self,
        dpi: int = 300,
        use_tex: bool = False,
        font_size: int = 10,
        rc_params: Optional[dict[str, Any]] = None,
    ) -> None:
        """Initialization.

        Args:
            dpi (int): The resolution in dots per inch for saved figures. Default is 300.
            use_tex (bool): Whether to use LaTeX for rendering text in figures. Default is False.
            font_size (int): The base font size for figure text. Default is 10.
            rc_params (Optional[dict[str, Any]]): Additional Matplotlib rcParams to customize figure style.
        """
        self.dpi = dpi
        self.use_tex = use_tex
        self.font_size = font_size
        self.set_style(rc_params)

    def set_style(self, rc_params: Optional[dict[str, Any]] = None) -> None:
        """Set the Matplotlib style for figures.

        Args:
            rc_params (Optional[dict[str, Any]]):
                Additional Matplotlib rcParams to customize figure style.
                This will override the default style settings if provided.
        """
        mpl.rcParams.update(
            {
                "font.size": self.font_size,
                "axes.titlesize": self.font_size,
                "axes.labelsize": self.font_size,
                "legend.fontsize": self.font_size - 1,
                "xtick.labelsize": self.font_size - 1,
                "ytick.labelsize": self.font_size - 1,
                "text.usetex": self.use_tex,
            }
        )
        if rc_params is not None:
            mpl.rcParams.update(rc_params)

    def save_to_pdf(
        self,
        figs: dict[str, Figure],
        parent_path: Path,
    ) -> None:
        """Save figures to PDF files in the specified directory.

        Args:
            figs (dict[str, Figure]): A dictionary
                mapping figure names to Matplotlib Figure objects.
            parent_path (Path): The directory path where
                the PDF files will be saved.
                The directory will be created if it does not exist.
        """
        if not parent_path.exists():
            parent_path.mkdir(parents=True)
        for name, fig in figs.items():
            fig.tight_layout()
            fig.savefig(
                parent_path / f"{name}.pdf",
                format="pdf",
                dpi=self.dpi,
                bbox_inches="tight",
                pad_inches=0.02,
            )
        plt.close(fig)


class AnalysisManager:
    """Manager class to run multiple analyzers and save their results and figures.

    Basic usage:
    >>> records = load_from_file("path/to/log.txt")
    >>> store = RecordStore(records)
    >>> analyzers = [ActionCounter(), FollowerCounter(), SalesAnalyzer()]
    >>> manager = AnalysisManager(analyzers)
    >>> results = manager.run_all(store, figs_save_path="path/to/save/figs")
    """

    def __init__(self, analyzers: list[AnalyzerBase[Any]]) -> None:
        """Initialization.

        Args:
            analyzers (list[AnalyzerBase[Any]]): A list of analyzer instances to run.
        """
        self.analyzers = analyzers

    def run_all(
        self,
        store: RecordStore,
        render_summary: bool = False,
        figs_save_path: Optional[str] = None,
    ) -> dict[str, Any]:
        """Run all analyzers and save their figures.

        Args:
            store (RecordStore): The record store to analyze.
            render_summary (bool): Whether to render a summary of the analysis results.
            figs_save_path (str, optional): The directory path to save figures.
        """
        results: dict[str, Any] = {}
        saver: FigureSaver = FigureSaver()
        for analyzer in self.analyzers:
            result: Any = analyzer.analyze(store)
            if render_summary:
                analyzer.summarize_results(result)
            results[analyzer.name] = result
            if figs_save_path is not None:
                figs: dict[str, Figure] = analyzer.draw_figs(result)
                saver.save_to_pdf(figs, pathlib.Path(figs_save_path))
        return results
