from __future__ import annotations

import pathlib
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Generic, Optional, TypeAlias, TypeVar, cast

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
from matplotlib.figure import Figure
from rich.console import Console, RenderableType
from rich.panel import Panel

from .records import AgentGenerationRecord
from .store import RecordStore

TimeKey: TypeAlias = int | datetime
T = TypeVar("T")


@dataclass(frozen=True)
class TimeAxisConfig:
    """Configuration for a shared simulation-step x-axis."""

    x_min: float
    x_max: float
    tick_positions: list[float]
    tick_labels: list[str]


class AnalyzerBase(ABC, Generic[T]):
    """Base class for log analyzers.

    Subclasses should implement :meth:`analyze` and :meth:`draw_figs`.

    This base class also provides shared utilities for time-series plots. In
    particular, :meth:`_prepare_time_axis` extracts the global time range from
    all records in a :class:`RecordStore`, and :meth:`_apply_time_axis` applies
    consistent x-axis limits and tick labels to Matplotlib axes.

    This makes figures generated by different analyzers comparable, because
    their x-axis ranges and tick labels can be aligned to the same global
    simulation period.

    Attributes:
        name: Unique analyzer name used for organizing output files.
    """

    name: str

    _time_axis_config: Optional[TimeAxisConfig] = None

    @abstractmethod
    def analyze(self, store: RecordStore) -> T:
        """Analyze records and return structured results."""

    @abstractmethod
    def draw_figs(self, result: T) -> dict[str, Figure]:
        """Draw figures from analysis results."""

    def _prepare_time_axis(
        self,
        store: RecordStore,
        *,
        max_ticks: int = 10,
    ) -> None:
        """Prepare a shared x-axis based on simulation time steps.

        The x-coordinate is always ``time_step``. Datetime values are used only as
        tick labels. This avoids inconsistent axes when datetime values are skipped
        or discontinuous due to inactive time ranges.
        """
        if max_ticks <= 0:
            raise ValueError("max_ticks must be positive.")

        step2time: dict[int, datetime] = {}
        step2fallback: set[int] = set()

        for record in store.records:
            maybe_step: object = getattr(record, "time_step", None)
            maybe_time: object = getattr(record, "time", None)
            if maybe_step == -1:
                continue

            if not isinstance(maybe_step, int):
                continue

            step2fallback.add(maybe_step)

            if isinstance(maybe_time, datetime):
                step2time[maybe_step] = maybe_time

        sorted_steps: list[int] = sorted(step2time)

        # Check datetime monotonicity. If broken, fall back to step labels.
        datetime_values: list[datetime] = [
            cast(datetime, step2time[step])
            for step in sorted_steps
            if isinstance(step2time[step], datetime)
        ]

        use_datetime_labels: bool = True
        if len(datetime_values) >= 2:
            use_datetime_labels = all(
                left <= right
                for left, right in zip(
                    datetime_values[:-1],
                    datetime_values[1:],
                    strict=True,
                )
            )

        min_step: int = sorted_steps[0]
        max_step: int = sorted_steps[-1]

        num_ticks: int = min(max_ticks, len(sorted_steps))
        tick_indices: list[int] = [
            int(round(value))
            for value in np.linspace(
                0,
                len(sorted_steps) - 1,
                num=num_ticks,
            )
        ]
        tick_indices = sorted(set(tick_indices))

        tick_steps: list[int] = [sorted_steps[index] for index in tick_indices]

        if use_datetime_labels:
            sorted_steps = sorted(step2fallback)
            tick_labels: list[str] = [
                self._format_time_key(step2time[step])
                if step in step2time
                else str(step)
                for step in tick_steps
            ]
        else:
            tick_labels = [str(step) for step in tick_steps]

        self._time_axis_config = TimeAxisConfig(
            x_min=float(min_step),
            x_max=float(max_step),
            tick_positions=[float(step) for step in tick_steps],
            tick_labels=tick_labels,
        )

    def _time_to_x(self, time_key: TimeKey) -> float:
        """Convert a time key to a numeric x-coordinate.

        Args:
            time_key: Integer time step or datetime.

        Returns:
            Numeric x-coordinate used for plotting.

        Raises:
            ValueError: If a datetime key is passed but no prepared time axis is
                available.
        """
        if isinstance(time_key, int):
            return float(time_key)

        if self._time_axis_config is None:
            raise ValueError(
                "Datetime x-values require _prepare_time_axis to be called first."
            )
        return float(time_key.timestamp())

    def _times_to_x(self, time_keys: list[TimeKey]) -> list[float]:
        """Convert time keys to numeric x-coordinates.

        Args:
            time_keys: List of integer or datetime time keys.

        Returns:
            Numeric x-coordinate list.
        """
        return [self._time_to_x(time_key) for time_key in time_keys]

    def _apply_time_axis(
        self,
        ax: Axes,
        *,
        rotate: int = 45,
        grid: bool = True,
    ) -> None:
        """Apply the prepared shared time-axis settings to an axis.

        Args:
            ax: Matplotlib axis to configure.
            rotate: Rotation angle for x-axis tick labels.
            grid: Whether to show a light grid.

        Raises:
            RuntimeError: If :meth:`_prepare_time_axis` has not been called.
        """
        if self._time_axis_config is None:
            raise RuntimeError("_prepare_time_axis must be called before plotting.")
        config: TimeAxisConfig = self._time_axis_config

        ax.set_xlim(config.x_min, config.x_max)
        ax.set_xticks(config.tick_positions)
        ax.set_xticklabels(
            config.tick_labels,
            rotation=rotate,
            ha="right",
            rotation_mode="anchor",
        )

        if grid:
            ax.grid(True, alpha=0.3)

    def _format_time_key(self, time_key: TimeKey) -> str:
        """Format a time key for axis labels and summaries.

        Args:
            time_key: Integer time step or datetime value.

        Returns:
            Human-readable time label.
        """
        if isinstance(time_key, datetime):
            return time_key.strftime("%Y-%m-%d\n %H:%M")

        return str(time_key)

    def get_agent_id2name(self, store: RecordStore) -> dict[int, str]:
        """Utility method to create a mapping from agent IDs to agent names using AgentGenerationRecord.

        Args:
            store (RecordStore): The record store containing the records to analyze.

        Returns:
            dict[int, str]: A dictionary mapping agent IDs to agent names.
        """
        agent_id2name: dict[int, str] = {}
        for record in store.typed(AgentGenerationRecord):
            agent_id2name[record.agent_id] = record.agent_name
        return agent_id2name

    def build_summary(self, result: T) -> RenderableType:
        """Build a rich-renderable summary of the analysis result.

        Subclasses can override this method.
        """
        return Panel.fit(
            f"No summary is implemented for [bold]{self.name}[/bold].",
            title="Analysis Summary",
            border_style="yellow",
        )

    def summarize_results(
        self,
        result: T,
        console: Optional[Console] = None,
    ) -> None:
        """Print the analysis summary using rich."""
        console = console or Console()
        console.print(self.build_summary(result))


class FigureSaver:
    """Utility class for saving figures generated by analyzers."""

    def __init__(
        self,
        dpi: int = 300,
        use_tex: bool = False,
        font_size: int = 10,
        rc_params: Optional[dict[str, Any]] = None,
    ) -> None:
        """Initialization.

        Args:
            dpi (int): The resolution in dots per inch for saved figures. Default is 300.
            use_tex (bool): Whether to use LaTeX for rendering text in figures. Default is False.
            font_size (int): The base font size for figure text. Default is 10.
            rc_params (Optional[dict[str, Any]]): Additional Matplotlib rcParams to customize figure style.
        """
        self.dpi = dpi
        self.use_tex = use_tex
        self.font_size = font_size
        self.set_style(rc_params)

    def set_style(self, rc_params: Optional[dict[str, Any]] = None) -> None:
        """Set the Matplotlib style for figures.

        Args:
            rc_params (Optional[dict[str, Any]]):
                Additional Matplotlib rcParams to customize figure style.
                This will override the default style settings if provided.
        """
        mpl.rcParams.update(
            {
                "font.size": self.font_size,
                "axes.titlesize": self.font_size,
                "axes.labelsize": self.font_size,
                "legend.fontsize": self.font_size - 1,
                "xtick.labelsize": self.font_size - 1,
                "ytick.labelsize": self.font_size - 1,
                "text.usetex": self.use_tex,
            }
        )
        if rc_params is not None:
            mpl.rcParams.update(rc_params)

    def save_to_pdf(
        self,
        figs: dict[str, Figure],
        parent_path: Path,
    ) -> None:
        """Save figures to PDF files in the specified directory.

        Args:
            figs (dict[str, Figure]): A dictionary
                mapping figure names to Matplotlib Figure objects.
            parent_path (Path): The directory path where
                the PDF files will be saved.
                The directory will be created if it does not exist.
        """
        if not parent_path.exists():
            parent_path.mkdir(parents=True)
        for name, fig in figs.items():
            fig.tight_layout()
            fig.savefig(
                parent_path / f"{name}.pdf",
                format="pdf",
                dpi=self.dpi,
                bbox_inches="tight",
                pad_inches=0.02,
            )
        plt.close(fig)


class AnalysisManager:
    """Manager class to run multiple analyzers and save their results and figures. Basic usage:

    >>> records = load_from_file("path/to/log.txt")
    >>> store = RecordStore(records)
    >>> analyzers = [ActionCounter(), FollowerCounter(), SalesAnalyzer()]
    >>> manager = AnalysisManager(analyzers)
    >>> results = manager.run_all(store, figs_save_path="path/to/save/figs")
    """

    def __init__(self, analyzers: list[AnalyzerBase[Any]]) -> None:
        """Initialization.

        Args:
            analyzers (list[AnalyzerBase[Any]]): A list of analyzer instances to run.
        """
        self.analyzers = analyzers

    def run_all(
        self,
        store: RecordStore,
        render_summary: bool = False,
        figs_save_path: Optional[str] = None,
    ) -> dict[str, Any]:
        """Run all analyzers and save their figures.

        Args:
            store (RecordStore): The record store to analyze.
            render_summary (bool): Whether to render a summary of the analysis results.
            figs_save_path (str, optional): The directory path to save figures.
        """
        results: dict[str, Any] = {}
        saver: FigureSaver = FigureSaver()
        for analyzer in self.analyzers:
            result: Any = analyzer.analyze(store)
            if render_summary:
                analyzer.summarize_results(result)
            results[analyzer.name] = result
            if figs_save_path is not None:
                figs: dict[str, Figure] = analyzer.draw_figs(result)
                saver.save_to_pdf(figs, pathlib.Path(figs_save_path))
        return results
