from __future__ import annotations

import random
from collections import deque
from typing import Any, Callable, Deque, Optional, Type

from ..logs import (
    AgentGenerationLog,
    ChangePriceLog,
    ConsumptionLog,
    FollowLog,
    InnerThoughtLog,
    Log,
    MoveLog,
    ObsLog,
    OrderExpirationLog,
    OrderLog,
    OrderReactionLog,
    ProposalExpirationLog,
    ProposalLog,
    ProposalReactionLog,
    SleepEndLog,
    SleepStartLog,
    SpaceAssignLog,
    StateEvaluationLog,
    TweetLog,
    UnfollowLog,
)
from ..sim_utils import find_class
from .memory_items import (
    AgentMemory,
    ConsumptionHistoryItem,
    ExchangeHistoryItem,
    InnerThoughtHistoryItem,
    MoveHistoryItem,
    ObsHistoryItem,
    PurchaseHistoryItem,
    SaleHistoryItem,
    SetPriceHistoryItem,
    SleepHistoryItem,
    SocialHistoryItem,
    StateEvaluationHistoryItem,
)
from .summarizer import MemorySummarizer


class MemoryHandler:
    """Memory Handler class."""

    def __init__(
        self,
        config: dict[str, Any],
        prng: Optional[random.Random] = None,
        registered_classes: list[Type] = [],
    ) -> None:
        """Initialization.

        Args:
            config (dict[str, Any]): the configuration for the MemoryHandler. It must contain the key:
                "memoryLength": defines the maximum length of the memory for each agent.
                "memorySummarizer": defines the summarizer to use for each type of history.
                and may contain:
                "numObs": the number of most recent observations to keep in memory.
                    Default to 1. Recommended to set numObs to be N * memoryLength, where N is the number of observation kinds.
            prng (random.Random, optional): the pseudo-random number generator to use.

        Note:
            MemoryHandler is generated by the environment as a part of service_dic.
            If the environment supports memory, it will call the MemoryHandler.update method
            to update the memory based on the logs generated in the environment.
            config example:
                "memoryHandler": {
                    "type": "MemoryHandler",
                    "memoryLength": int,
                    "memorySummarizer": {
                        "type": "MemorySummarizer",
                    }
                }
        """
        self.config: dict[str, Any] = config
        if "memoryLength" in self.config:
            self.memory_length: int = self.config["memoryLength"]
        else:
            raise ValueError(
                "memoryLength must be specified in the config for MemoryHandler."
            )
        assert 1 <= self.memory_length, "memoryLength must be at least 1."
        if "memorySummarizer" in self.config:
            summarizer_config: dict[str, Any] = self.config["memorySummarizer"]
            if "type" not in summarizer_config:
                raise ValueError(
                    "type must be specified in memorySummarizer config for MemoryHandler."
                )
            summarizer_type: str = summarizer_config["type"]
            summarizer_class: Type[MemorySummarizer] = find_class(
                summarizer_type, registered_classes
            )
            self.memory_summarizer: MemorySummarizer = summarizer_class(
                summarizer_config, prng, registered_classes
            )
        else:
            raise ValueError(
                "memorySummarizer must be specified in the config for MemoryHandler."
            )
        self.prng: random.Random = prng if prng is not None else random.Random()
        self.agent_id2memory: dict[int, AgentMemory] = {}
        self.memory_updaters: dict[type[Log], Callable[[Any], None]] = (
            self._build_memory_registry()
        )
        self.num_obs: int = self.config.get("numObs", 1)
        self.current_time: int | str = -1
        self.current_time_step: int = -1

    def get_memory(self, agent_id: int) -> dict[str, Any]:
        """Summarize and return the memory of the agent with the given agent_id.

        Args:
            agent_id (int): the id of the agent whose memory is to be retrieved.

        Returns:
            dict[str, Any]: the summarized memory of the agent.

        Note:
            Memory is provided as a part of the observation to the agent.
            econsimulacra.envs.obs_providers.MemoryProvider calls this method to get the memory of the agent.
            See also: econsimulacra.envs.obs_providers.MemoryProvider

            The structure of the summarized memory is::

                {
                    "memory_length": int,
                    "sleep_history": "slept from time to time, ...",
                    "move_history": "(x0,y0) -> (x1,y1) -> (x2,y2)",
                    "consumption_history": "item_name x quantity at time, ...",
                    "purchase_history": "item_name x quantity at price from agent_id at time, ...",
                    "sale_history": "item_name x quantity at price to agent_id at time, ...",
                    "exchange_history": "give item_name x quantity, get item_name x quantity with agent_id at time; ...",
                    "set_price_history": "item_name: old_price -> new_price at time, ...",
                    "social_history": "follow target_agent_id at time (num_followers: N, num_follows: M); ...",
                    "state_evaluation_history": "Wealth: wealth at time; ...",
                }
        """
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        summarized_memory: dict[str, Any] = self.summarize_memory(agent_memory)
        return summarized_memory

    def summarize_memory(self, agent_memory: AgentMemory) -> dict[str, Any]:
        return self.memory_summarizer.summarize_memory(agent_memory)

    def _build_memory_registry(self) -> dict[type[Log], Callable[[Any], None]]:
        """Build a dispatch dictionary that maps log types to their corresponding memory update handlers.

        Returns:
            dict[type[Log], Callable[[Any], None]]: a dictionary mapping log types to memory update handlers.

        Note:
            _process_{log_type}_log methods are defined for each log type to update the memory based on the log.
            You can implement specific memory update logic in these methods.
        """
        return {
            AgentGenerationLog: self._process_agent_generation_log,
            SpaceAssignLog: self._process_space_assign_log,
            SleepStartLog: self._process_sleep_start_log,
            SleepEndLog: self._process_sleep_end_log,
            MoveLog: self._process_move_log,
            ConsumptionLog: self._process_consumption_log,
            OrderLog: self._process_order_log,
            OrderExpirationLog: self._process_order_expiration_log,
            ProposalLog: self._process_proposal_log,
            ProposalExpirationLog: self._process_proposal_expiration_log,
            OrderReactionLog: self._process_order_reaction_log,
            ProposalReactionLog: self._process_proposal_reaction_log,
            ChangePriceLog: self._process_change_price_log,
            InnerThoughtLog: self._process_inner_thought_log,
            TweetLog: self._process_tweet_log,
            FollowLog: self._process_follow_log,
            UnfollowLog: self._process_unfollow_log,
            StateEvaluationLog: self._process_state_evaluation_log,
            ObsLog: self._process_obs_log,
        }

    def update(self, log: Log) -> None:
        """Update memory based on the log. This method is called by the environment.

        Note:
            See also:
                econsimulacra.envs.base.Environment.remember_log(log: Log)
        """
        self._update_time(log)
        for log_type, handler in self.memory_updaters.items():
            if isinstance(log, log_type):
                handler(log)
                return

    def _update_time(self, log: Log) -> None:
        """Update the current time and time step based on the log."""
        t: Optional[int | str] = getattr(log, "time", None)
        time_step: Optional[int] = getattr(log, "time_step", None)
        if t is not None:
            self.current_time = t
        if time_step is not None:
            self.current_time_step = time_step
        self.memory_summarizer.sync_time(self.current_time, self.current_time_step)

    def _process_agent_generation_log(self, log: AgentGenerationLog) -> None:
        """Process the AgentGenerationLog to initialize AgentMemory for the generated agent.

        Args:
            log (AgentGenerationLog): the log of agent generation.

        See also:
            econsimulacra.envs.memory.AgentMemory
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            agent_memory: AgentMemory = AgentMemory(
                consumption_history=deque(maxlen=self.memory_length),
                move_history=deque(maxlen=self.memory_length),
                sleep_history=deque(maxlen=self.memory_length),
                purchase_history=deque(maxlen=self.memory_length),
                sale_history=deque(maxlen=self.memory_length),
                exchange_history=deque(maxlen=self.memory_length),
                set_price_history=deque(maxlen=self.memory_length),
                inner_thought_history=deque(maxlen=self.memory_length),
                social_history=deque(maxlen=self.memory_length),
                state_evaluation_history=deque(maxlen=self.memory_length),
                obs_history=deque(maxlen=self.memory_length * self.num_obs),
            )
            agent_memory.state_evaluation_history.append(
                StateEvaluationHistoryItem(
                    wealth=log.wealth,
                    relative_wealth=None,
                    buying_power=None,
                    inventory_dic=log.inventory_dic,
                    persona_dic=log.persona_dic,
                    time=log.time,
                    time_step=log.time_step,
                )
            )
            self.agent_id2memory[agent_id] = agent_memory
        else:
            raise ValueError(f"Agent with id {agent_id} already exists in memory.")

    def _process_space_assign_log(self, log: SpaceAssignLog) -> None:
        """Process the SpaceAssignLog to update the initial position of the agent in memory.

        Args:
            log (SpaceAssignLog): the log of space assignment.

        Note:
            Generate a new MoveHistoryItem and add it to the move_history of the agent's memory.
            The time of this MoveHistoryItem can be set to None, indicating that
            it is the initial position assigned by the environment.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        move_history: Deque[MoveHistoryItem] = agent_memory.move_history
        if len(move_history) > 0:
            raise ValueError(
                f"Agent with id {agent_id} already has a position assigned in memory."
            )
        move_history.append(
            MoveHistoryItem(pos=log.pos, init_pos=log.pos, time=None, time_step=-1)
        )

    def _process_sleep_start_log(self, log: SleepStartLog) -> None:
        """Process the SleepStartLog to update the sleep history of the agent in memory.

        Args:
            log (SleepStartLog): the log of sleep start.

        Note:
            Generate a new SleepHistoryItem and add it to the sleep_history of the agent's memory.
            The time of this SleepHistoryItem is log.time, indicating the time when the agent starts sleeping.
            The end_time of this SleepHistoryItem is set to None, indicating that the agent is still sleeping.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        sleep_history: Deque[SleepHistoryItem] = agent_memory.sleep_history
        sleep_history.append(
            SleepHistoryItem(
                start_time=log.time,
                end_time=None,
            )
        )

    def _process_sleep_end_log(self, log: SleepEndLog) -> None:
        """Process the SleepEndLog to update the sleep history of the agent in memory.

        Args:
            log (SleepEndLog): the log of sleep end.

        Note:
            Find the last SleepHistoryItem in the sleep_history of the agent's memory whose end_time is None,
            and update its end_time to the time in the log.
            If there is no SleepHistoryItem with end_time None, raise an error.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        sleep_history: Deque[SleepHistoryItem] = agent_memory.sleep_history
        latest_sleep_history: Optional[SleepHistoryItem] = (
            sleep_history[-1] if sleep_history else None
        )
        if latest_sleep_history is None:
            raise ValueError(
                f"Agent with id {agent_id} has no sleep history in memory, but received SleepEndLog."
            )
        if latest_sleep_history.end_time is not None:
            raise ValueError(
                f"Agent with id {agent_id} has no ongoing sleep in memory, but received SleepEndLog."
            )
        latest_sleep_history.end_time = log.time

    def _process_move_log(self, log: MoveLog) -> None:
        """Process the MoveLog to update the position of the agent in memory.

        Args:
            log (MoveLog): the log of movement.

        Note:
            Generate a new MoveHistoryItem and add it to the move_history of the agent's memory.
            The time of this MoveHistoryItem is log.time, indicating the time of the movement.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        move_history: Deque[MoveHistoryItem] = agent_memory.move_history
        old_pos: Optional[tuple[int, ...]] = (
            move_history[-1].pos if move_history else None
        )
        old_pos_in_log: tuple[int, ...] = log.old_pos
        if old_pos != old_pos_in_log:
            raise ValueError(
                f"Agent with id {agent_id} has a different position in memory ({old_pos}) and in log ({old_pos_in_log})."
            )
        move_history.append(
            MoveHistoryItem(
                pos=log.new_pos,
                init_pos=log.init_pos,
                time=log.time,
                time_step=log.time_step,
            )
        )

    def _process_consumption_log(self, log: ConsumptionLog) -> None:
        """Process the ConsumptionLog to update the consumption history of the agent in memory.

        Args:
            log (ConsumptionLog): the log of consumption.

        Note:
            Generate a new ConsumptionHistoryItem and add it to the consumption_history of the agent's memory.
            If the last consumption in the consumption_history has the same item_name and time as the current log,
            update the quantity of the last consumption instead of adding a new item to the history.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        consumption_history: Deque[ConsumptionHistoryItem] = (
            agent_memory.consumption_history
        )
        last_consumption: Optional[ConsumptionHistoryItem] = (
            consumption_history[-1] if consumption_history else None
        )
        if last_consumption is not None:
            last_consumption_time: int | str = last_consumption.time
            last_consumption_item_name: str = last_consumption.item_name
            if (
                last_consumption_time == log.time
                and last_consumption_item_name == log.item_name
            ):
                consumption_history[-1].quantity += log.item_amount
                return
        consumption_history.append(
            ConsumptionHistoryItem(
                item_name=log.item_name,
                quantity=log.item_amount,
                time=log.time,
                time_step=log.time_step,
            )
        )

    def _process_order_log(self, log: OrderLog) -> None:
        """Process the OrderLog to update the order history of the agent in memory.

        Args:
            log (OrderLog): the log of order.

        Note:
            Not implemented yet.
        """
        pass

    def _process_order_expiration_log(self, log: OrderExpirationLog) -> None:
        """Process the OrderExpirationLog to update the order history of the agent in memory.

        Args:
            log (OrderExpirationLog): the log of order expiration.

        Note:
            Not implemented yet.
        """
        pass

    def _process_proposal_log(self, log: ProposalLog) -> None:
        """Process the ProposalLog to update the proposal history of the agent in memory.

        Args:
            log (ProposalLog): the log of proposal.

        Note:
            Not implemented yet.
        """
        pass

    def _process_proposal_expiration_log(self, log: ProposalExpirationLog) -> None:
        """Process the ProposalExpirationLog to update the proposal history of the agent in memory.

        Args:
            log (ProposalExpirationLog): the log of proposal expiration.

        Note:
            Not implemented yet.
        """
        pass

    def _process_order_reaction_log(self, log: OrderReactionLog) -> None:
        """Process the OrderReactionLog to update the purchase and sale history of the agents in memory based on the reaction.

        Args:
            log (OrderReactionLog): the log of order reaction.

        Note:
            Order reaction event affects both buyer's and seller's memory.
            Each update method for buyer and seller is implemented in
            _process_order_reaction_log_purchase_agent and _process_order_reaction_log_sale_agent, respectively.
        """
        purchase_agent_id: int = log.agent_id
        sale_agent_id: int = log.counterparty_id
        if purchase_agent_id not in self.agent_id2memory:
            raise ValueError(
                f"Agent with id {purchase_agent_id} does not exist in memory."
            )
        if sale_agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {sale_agent_id} does not exist in memory.")
        self._process_order_reaction_log_purchase_agent(log)
        self._process_order_reaction_log_sale_agent(log)

    def _process_order_reaction_log_purchase_agent(self, log: OrderReactionLog) -> None:
        """Process the OrderReactionLog to update the purchase history of the purchase agent in memory.

        Args:
            log (OrderReactionLog): the log of order reaction.

        Note:
            If the reaction is accept, generate a new PurchaseHistoryItem and add it
            to the purchase_history of the purchase agent's memory.
            If the last purchase in the purchase_history has the same item_name, time, and from_agent_id
            as the current log, update the quantity of the last purchase instead of
            adding a new item to the history.
        """
        purchase_agent_id: int = log.agent_id
        sale_agent_id: int = log.counterparty_id
        purchase_agent_memory: AgentMemory = self.agent_id2memory[purchase_agent_id]
        purchase_history: Deque[PurchaseHistoryItem] = (
            purchase_agent_memory.purchase_history
        )
        last_purchase: Optional[PurchaseHistoryItem] = (
            purchase_history[-1] if purchase_history else None
        )
        if last_purchase is not None:
            last_purchase_time: int | str = last_purchase.time
            last_purchase_item_name: str = last_purchase.item_name
            last_purchase_from: int = last_purchase.from_agent_id
            if (
                last_purchase_time == log.time
                and last_purchase_item_name == log.item_name
                and last_purchase_from == sale_agent_id
            ):
                purchase_history[-1].quantity += log.accept_amount
                return
        purchase_history.append(
            PurchaseHistoryItem(
                item_name=log.item_name,
                quantity=log.accept_amount,
                price=log.price,
                time=log.time,
                time_step=log.time_step,
                from_agent_id=sale_agent_id,
            )
        )

    def _process_order_reaction_log_sale_agent(self, log: OrderReactionLog) -> None:
        """Process the OrderReactionLog to update the sale history of the sale agent in memory.

        Args:
            log (OrderReactionLog): the log of order reaction.

        Note:
            If the reaction is accept, generate a new SaleHistoryItem and add it
            to the sale_history of the sale agent's memory.
            If the last sale in the sale_history has the same item_name, time, and to_agent_id
            as the current log, update the quantity of the last sale instead of
            adding a new item to the history.
        """
        purchase_agent_id: int = log.agent_id
        sale_agent_id: int = log.counterparty_id
        sale_agent_memory: AgentMemory = self.agent_id2memory[sale_agent_id]
        sale_history: Deque[SaleHistoryItem] = sale_agent_memory.sale_history
        last_sale: Optional[SaleHistoryItem] = (
            sale_history[-1] if sale_history else None
        )
        if last_sale is not None:
            last_sale_time: int | str = last_sale.time
            last_sale_item_name: str = last_sale.item_name
            last_sale_to: int = last_sale.to_agent_id
            if (
                last_sale_time == log.time
                and last_sale_item_name == log.item_name
                and last_sale_to == purchase_agent_id
            ):
                sale_history[-1].quantity += log.accept_amount
                return
        sale_history.append(
            SaleHistoryItem(
                item_name=log.item_name,
                quantity=log.accept_amount,
                price=log.price,
                time=log.time,
                time_step=log.time_step,
                to_agent_id=purchase_agent_id,
            )
        )

    def _process_proposal_reaction_log(self, log: ProposalReactionLog) -> None:
        """Process the ProposalReactionLog to update the exchange history of the proposer and responder agents in memory based on the reaction.

        Args:
            log (ProposalReactionLog): the log of proposal reaction.

        Note:
            Proposal reaction event affects both proposer's and responder's memory.
            Each update method for proposer and responder is implemented in
            _process_proposal_reaction_log_proposer_agent and _process_proposal_reaction_log_responder_agent, respectively.
        """
        if not log.accept:
            return
        proposer_agent_id: int = log.proposer_agent_id
        responder_agent_id: int = log.responder_agent_id
        if proposer_agent_id not in self.agent_id2memory:
            raise ValueError(
                f"Agent with id {proposer_agent_id} does not exist in memory."
            )
        if responder_agent_id not in self.agent_id2memory:
            raise ValueError(
                f"Agent with id {responder_agent_id} does not exist in memory."
            )
        if log.accept:
            self._process_proposal_reaction_log_proposer_agent(log)
            self._process_proposal_reaction_log_responder_agent(log)

    def _process_proposal_reaction_log_proposer_agent(
        self, log: ProposalReactionLog
    ) -> None:
        """Process the ProposalReactionLog to update the exchange history of the proposer agent in memory.

        Args:
            log (ProposalReactionLog): the log of proposal reaction.

        Note:
            If the reaction is accept, generate a new ExchangeHistoryItem
            and add itto the exchange_history of the proposer agent's memory.
            If the last exchange in the exchange_history has the same give_item_name,
            get_item_name, time, and counterparty_id as the current log,
            update the give_item_quantity and get_item_quantity of the last exchange.
        """
        proposer_agent_id: int = log.proposer_agent_id
        responder_agent_id: int = log.responder_agent_id
        proposer_agent_memory: AgentMemory = self.agent_id2memory[proposer_agent_id]
        exchange_history: Deque[ExchangeHistoryItem] = (
            proposer_agent_memory.exchange_history
        )
        exchange_history.append(
            ExchangeHistoryItem(
                give_item_name=log.give_item_name,
                give_item_quantity=log.give_item_amount,
                get_item_name=log.get_item_name,
                get_item_quantity=log.get_item_amount,
                time=log.time,
                time_step=log.time_step,
                counterparty_id=responder_agent_id,
            )
        )

    def _process_proposal_reaction_log_responder_agent(
        self, log: ProposalReactionLog
    ) -> None:
        """Process the ProposalReactionLog to update the exchange history of the responder agent in memory.

        Args:
            log (ProposalReactionLog): the log of proposal reaction.

        Note:
            If the reaction is accept, generate a new ExchangeHistoryItem
            and add itto the exchange_history of the responder agent's memory.
            If the last exchange in the exchange_history has the same give_item_name,
            get_item_name, time, and counterparty_id as the current log,
            update the give_item_quantity and get_item_quantity of the last exchange.
        """
        proposer_agent_id: int = log.proposer_agent_id
        responder_agent_id: int = log.responder_agent_id
        responder_agent_memory: AgentMemory = self.agent_id2memory[responder_agent_id]
        exchange_history: Deque[ExchangeHistoryItem] = (
            responder_agent_memory.exchange_history
        )
        exchange_history.append(
            ExchangeHistoryItem(
                give_item_name=log.get_item_name,
                give_item_quantity=log.get_item_amount,
                get_item_name=log.give_item_name,
                get_item_quantity=log.give_item_amount,
                time=log.time,
                time_step=log.time_step,
                counterparty_id=proposer_agent_id,
            )
        )

    def _process_change_price_log(self, log: ChangePriceLog) -> None:
        """Process the ChangePriceLog to update the price change history of the agent in memory.

        Args:
            log (ChangePriceLog): the log of price change.

        Note:
            Generate a new SetPriceHistoryItem and add it to the set_price_history of the agent's memory.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        set_price_history: Deque[SetPriceHistoryItem] = agent_memory.set_price_history
        set_price_history.append(
            SetPriceHistoryItem(
                item_name=log.item_name,
                old_price=log.old_price,
                new_price=log.new_price,
                time=log.time,
                time_step=log.time_step,
            )
        )

    def _process_inner_thought_log(self, log: InnerThoughtLog) -> None:
        """Process the InnerThoughtLog to update the inner thought history of the agent in memory.

        Args:
            log (InnerThoughtLog): the log of inner thought.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        inner_thought_history: Deque[InnerThoughtHistoryItem] = (
            agent_memory.inner_thought_history
        )
        inner_thought_history.append(
            InnerThoughtHistoryItem(
                inner_thought=log.inner_thought,
                time=log.time,
                time_step=log.time_step,
            )
        )

    def _process_tweet_log(self, log: TweetLog) -> None:
        """Process the TweetLog to update the tweet history of the agent in memory.

        Args:
            log (TweetLog): the log of tweet.

        Note:
            Not implemented yet.
        """
        pass

    def _process_follow_log(self, log: FollowLog) -> None:
        """Process the FollowLog to update the social action history of the agent in memory.

        Args:
            log (FollowLog): the log of follow action.

        Note:
            Generate a new SocialHistoryItem and add it to the social_history of the agent's memory.
            The action attribute of the SocialHistoryItem is set to "follow".
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        social_history: Deque[SocialHistoryItem] = agent_memory.social_history
        social_history.append(
            SocialHistoryItem(
                action="follow",
                target_agent_id=log.target_agent_id,
                time=log.time,
                time_step=log.time_step,
                num_followers=log.num_followers,
                num_follows=log.num_follows,
            )
        )

    def _process_unfollow_log(self, log: UnfollowLog) -> None:
        """Process the UnfollowLog to update the social action history of the agent in memory.

        Args:
            log (UnfollowLog): the log of unfollow action.

        Note:
            Generate a new SocialHistoryItem and add it to the social_history of the agent's memory.
            The action attribute of the SocialHistoryItem is set to "unfollow".
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        social_history: Deque[SocialHistoryItem] = agent_memory.social_history
        social_history.append(
            SocialHistoryItem(
                action="unfollow",
                target_agent_id=log.target_agent_id,
                time=log.time,
                time_step=log.time_step,
                num_followers=log.num_followers,
                num_follows=log.num_follows,
            )
        )

    def _process_state_evaluation_log(self, log: StateEvaluationLog) -> None:
        """Process the StateEvaluationLog to update the state evaluation history of the agent in memory.

        Args:
            log (StateEvaluationLog): the log of state evaluation.

        Note:
            Generate a new StateEvaluationItem and add it to the state_evaluation_history of the agent's memory.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        state_evaluation_history: Deque[StateEvaluationHistoryItem] = (
            agent_memory.state_evaluation_history
        )
        state_evaluation_history.append(
            StateEvaluationHistoryItem(
                wealth=log.wealth,
                relative_wealth=log.relative_wealth,
                buying_power=log.buying_power,
                inventory_dic=log.inventory_dic,
                persona_dic=log.persona_dic,
                time=log.time,
                time_step=log.time_step,
            )
        )

    def _process_obs_log(self, log: ObsLog) -> None:
        """Process the ObsLog to update the observation history of the agent in memory.

        Args:
            log (ObsLog): the log of observation.

        Note:
            Generate a new ObsHistoryItem and add it to the obs_history of the agent's memory.
        """
        agent_id: int = log.agent_id
        if agent_id not in self.agent_id2memory:
            raise ValueError(f"Agent with id {agent_id} does not exist in memory.")
        agent_memory: AgentMemory = self.agent_id2memory[agent_id]
        obs_history: Deque[ObsHistoryItem] = agent_memory.obs_history
        obs_history.append(
            ObsHistoryItem(
                obs_type=log.obs_type,
                time=log.time,
                time_step=log.time_step,
                obs=log.obs,
            )
        )
