from random import Random
from typing import Any, Optional, Type

from ..sim_utils import find_class
from .recsys import RecommenderSystem


class SocialNetwork:
    """Social Network class.

    The SocialNetwork class represents a social network environment where agents can tweet messages and follow/unfollow other agents.
    """

    def __init__(
        self, config: dict[str, Any], registered_classes: list[Type], prng: Random
    ) -> None:
        """Initialization. SocialNetwork is usually generated by the environment.

        Args:
            config (dict): Configuration dictionary for the social network. This must include:
                - recSys: Configuration dictionary for the recommender system.
                    See also: econsimulacra.envs.social_networks.recsys.RecommenderSystem
                and may include:
                - followCap: Optional integer specifying the maximum number of agents that any agent can follow.
                    If not provided, there is no limit on the number of follows.
            registered_classes (list[Type]): A list of registered classes for class instantiation.
                This is used to find the recommender system class based on the "type" specified in the recSys config.
                You can register custom recommender systems class by econsimulacra.envs.base.Environment.register_class
            prng (Random): A pseudo random number generator.

        Note:
            See also:
                econsimulacra.envs.base.Environment._generate_social_network(social_network_key: str)
        """
        self.config: dict[str, Any] = config
        self.prng: Random = prng
        self.nodes: set[int] = set()
        self.follow_cap: Optional[int] = config.get("followCap")
        self.agent_id2agent_name: dict[int, str] = {}
        self.agent_id2tweet: dict[int, str] = {}
        self.agent_id2followers: dict[int, set[int]] = {}
        self.agent_id2follows: dict[int, set[int]] = {}
        if "recSys" not in config:
            raise ValueError(
                "Recommender system configuration is missing in the social network config."
            )
        self.rec_sys: RecommenderSystem = self._generate_rec_sys(
            config["recSys"], registered_classes, prng
        )
        self.rec_sys.bind(self)

    def _generate_rec_sys(
        self,
        recsys_config: dict[str, Any],
        registered_classes: list[Type],
        prng: Random,
    ) -> RecommenderSystem:
        """Generate the recommender system based on the configuration. Called during initialization.

        Args:
            recsys_config (dict): Configuration dictionary for the recommender system. This must include:
                - type: A string specifying the type of the recommender system. This is used to find the corresponding class in the registered classes.
                and may include other configuration parameters specific to the recommender system.
            registered_classes (list[Type]): A list of registered classes for class instantiation.
                This is used to find the recommender system class based on the "type" specified in the recsys_config.
                You can register custom recommender systems class by econsimulacra.envs.base.Environment.register_class
            prng (Random): A pseudo random number generator. This is passed to the recommender system during initialization.

        Returns:
            RecommenderSystem: An instance of the recommender system. This becomes the rec_sys attribute of the SocialNetwork.
        """
        recsys_type: str = recsys_config.get("type", "RecommenderSystem")
        recsys_class: Type[RecommenderSystem] = find_class(
            recsys_type, registered_classes
        )
        recsys: RecommenderSystem = recsys_class(config=recsys_config, prng=prng)
        return recsys

    def add_agent(self, agent_id: int, agent_name: str) -> None:
        """Add a new agent to the SocialNetwork.

        Args:
            agent_id (int): The agent ID for the agent to be added.

        Note:
            See also:
                econsimulacra.envs.base.Environment._generate_agents
        """
        if agent_id in self.nodes:
            raise ValueError(
                f"Agent ID {agent_id} already exists in the social network."
            )
        self.nodes.add(agent_id)
        self.agent_id2agent_name[agent_id] = agent_name
        self.agent_id2tweet[agent_id] = ""
        self.agent_id2followers[agent_id] = set()
        self.agent_id2follows[agent_id] = set()
        self.rec_sys.hook_add_agent(agent_id, agent_name)

    def tweet(self, agent_id: int, message: str) -> None:
        """Append a new message to the agent's existing tweet. This represents the agent tweeting a message in the social network.

        Args:
            agent_id (int): The agent ID of the agent that tweeted.
            message (str): The content of the tweet.

        Note:
            See also:
                econsimulacra.envs.base.Environment._act_in_social_network
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        self.agent_id2tweet[agent_id] = message
        self.rec_sys.hook_tweet(agent_id, message)

    def follow_agent(self, agent_id: int, target_agent_id: int) -> None:
        """Update the social network to reflect that the agent with agent_id follows the agent with target_agent_id.

        Args:
            agent_id (int): The agent IDthat wants to follow another agent.
            target_agent_id (int): The agent ID to be followed.

        Note:
            See also:
                econsimulacra.envs.base.Environment._act_in_social_network
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        if target_agent_id not in self.nodes:
            raise ValueError(
                f"Target Agent ID {target_agent_id} not found in the social network."
            )
        if target_agent_id == agent_id:
            raise ValueError("An agent cannot follow itself.")
        follow_count: int = len(self.agent_id2follows[agent_id])
        if self.follow_cap is not None and follow_count >= self.follow_cap:
            raise ValueError(
                f"Agent ID {agent_id} has reached the follow cap of {self.follow_cap}."
            )
        self.agent_id2follows[agent_id].add(target_agent_id)
        self.agent_id2followers[target_agent_id].add(agent_id)
        self.rec_sys.hook_follow_agent(agent_id, target_agent_id)

    def unfollow_agent(self, agent_id: int, target_agent_id: int) -> None:
        """Update the social network to reflect that the agent with agent_id unfollows the agent with target_agent_id.

        Args:
            agent_id (int): The agent IDthat wants to unfollow another agent.
            target_agent_id (int): The agent ID to be unfollowed.

        Note:
            See also:
                econsimulacra.envs.base.Environment._act_in_social_network
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        if target_agent_id not in self.nodes:
            raise ValueError(
                f"Target Agent ID {target_agent_id} not found in the social network."
            )
        if target_agent_id not in self.agent_id2follows[agent_id]:
            raise ValueError(
                f"Agent ID {agent_id} does not follow Agent ID {target_agent_id}."
            )
        if agent_id not in self.agent_id2followers[target_agent_id]:
            raise ValueError(
                f"Agent ID {target_agent_id} does not have Agent ID {agent_id} as a follower."
            )
        self.agent_id2follows[agent_id].remove(target_agent_id)
        self.agent_id2followers[target_agent_id].remove(agent_id)
        self.rec_sys.hook_unfollow_agent(agent_id, target_agent_id)

    def get_followers(self, agent_id: int) -> set[int]:
        """Get the agent IDs that follow the agent with the given agent_id.

        Args:
            agent_id (int): The agent ID for which to get the followers.

        Returns:
            set[int]: A set of agent IDs that follow the given agent.
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        return self.agent_id2followers[agent_id]

    def get_num_followers(self, agent_id: int) -> int:
        """Get the number of followers for the agent with the given agent_id.

        Args:
            agent_id (int): The agent ID for which to get the number of followers.

        Returns:
            int: The number of followers for the given agent.
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        return len(self.agent_id2followers[agent_id])

    def get_follow_cap(self) -> Optional[int]:
        """Get the follow cap of the social network.

        Returns:
            int, optional: The follow cap of the social network, or None if not set.
        """
        return self.follow_cap

    def get_allowed_num_follows(self, agent_id: int) -> Optional[int]:
        """Get the allowed number of follows for the agent with the given agent_id,
        which is the remaining number of follows the agent can make before reaching the follow cap.

        Args:
            agent_id (int): The agent ID for which to get the allowed number of follows.

        Returns:
            int, optional: The allowed number of follows for the given agent, or None if there is no follow cap.
        """
        if self.follow_cap is None:
            return None
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        current_follow_count: int = len(self.agent_id2follows[agent_id])
        allowed_num_follows: int = self.follow_cap - current_follow_count
        return allowed_num_follows

    def get_follows(self, agent_id: int) -> set[int]:
        """Get the agent IDs that the agent with the given agent_id follows.

        Args:
            agent_id (int): The agent ID for which to get the follows.

        Returns:
            set[int]: A set of agent IDs that the given agent follows.
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        return self.agent_id2follows[agent_id]

    def get_num_follows(self, agent_id: int) -> int:
        """Get the number of follows for the agent with the given agent_id.

        Args:
            agent_id (int): The agent ID for which to get the number of follows.

        Returns:
            int: The number of follows for the given agent.
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        return len(self.agent_id2follows[agent_id])

    def get_tweet(self, agent_id: int) -> str:
        """Get the latest tweet of the agent with the given agent_id.

        Args:
            agent_id (int): The agent ID for which to get the latest tweet.

        Returns:
            str: The latest tweet of the given agent.
        """
        if agent_id not in self.nodes:
            raise ValueError(f"Agent ID {agent_id} not found in the social network.")
        return self.agent_id2tweet[agent_id]

    def get_recommended_follows(self, agent_id: int) -> list[int]:
        """Get a list of recommended agent IDs for the agent with the given agent_id to follow, based on the recommender system.

        Args:
            agent_id (int): The agent ID for which to get the recommended follows.

        Returns:
            list[int]: A list of recommended agent IDs for the given agent to follow.

        Note:
            The recommendations are generated based on the recommender system's algorithm.
            See also: econsimulacra.social_networks.recsys.RecommenderSystem,
            econsimulacra.envs.obs_providers.RecommendedFollowsProvider
        """
        recommended_follows: list[int] = self.rec_sys.get_recommendations(
            agent_id=agent_id
        )
        return recommended_follows
